# name of the software
name: Check Yo Self

project:
    version: 0.0.1
    download_url: https://github.com/twhite96/checkyoself/releases

license:
    software: MIT License
    software_url: http://opensource.org/licenses/MIT

    docs: CC BY 3.0
    docs_url: http://creativecommons.org/licenses/by/3.0/

links:
    header:
      - title: GitHub
        url: https://github.com/twhite96/checkyoself
    footer:
      - title: GitHub
        url: https://github.com/twhite96/checkyoself
      - title: Issues
        url: https://github.com/twhite96/checkyoself/issues?state=open

ui:
    header:
        color1: "#069690"
        color2: "#06D7D9"
        trianglify: true

social:
    github:
        user: twhite96
        repo: checkyoself
    twitter:
        enabled: true
        via:
        hash:
        account:
    facebook:
        enabled: false
        profileUrl:

analytics:
    google: UA-123456-1

# Build settings
markdown: kramdown
exclude:
    - Gemfile
    - Gemfile.lock
